//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property.Property1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Property1.MLSDataWebServiceSoap")]
    public interface MLSDataWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResidentialProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetResidentialProperties(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResidentialPropertiesDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetResidentialPropertiesDetail(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResidentialPropertiesTop3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetResidentialPropertiesTop3(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResidentialPropertiesTop10", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetResidentialPropertiesTop10(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPropertyTypesResidential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPropertyTypesResidential();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPropertyTypesCommercial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPropertyTypesCommercial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPropertyTypesCondo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPropertyTypesCondo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPropertyTypesByMLSID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPropertyTypesByMLSID(string mlsid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSaleLeaseResidential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSaleLeaseResidential();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSaleLeaseCommercial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSaleLeaseCommercial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSaleLeaseCondo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSaleLeaseCondo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImageByMLSID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetImageByMLSID(string MLSID_City_PostalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommercialPropertiesByMLSID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCommercialPropertiesByMLSID(string MLSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommercialProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllCommercialProperties(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BathRooms, string SaleLease);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCommercialPropertiesTop3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllCommercialPropertiesTop3(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BathRooms, string SaleLease);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeatureListing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FeatureListing(string MLSIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProperties_Condo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProperties_Condo(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProperties_CondoTop3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProperties_CondoTop3(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease, string Top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPropertiesByMLSID_Condo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPropertiesByMLSID_Condo(string MLSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAutoCompleteData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAutoCompleteData(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAutoCompleteData_Comm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAutoCompleteData_Comm(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAutoCompleteData_Condo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAutoCompleteData_Condo(string prefixText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllFeatures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllFeatures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFeatures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteFeatures(string MLSIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllVirtualTourData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllVirtualTourData(int startindex, int pagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVirtualTourData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVirtualTourData(string MLSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertVertualTourImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertVertualTourImages(string MLSID, string VimageBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidMLSID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsValidMLSID(string MLSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Registration(string name, string emailID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AuthenticateUser(string emailid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertVertualDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertVertualDetails(string virtualname, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertImageByVirtualName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertImageByVirtualName(string VirtualID, int userid, string VimageBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrSingleVirtDetailsByVid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllOrSingleVirtDetailsByVid(int userid, int startindex, int endindex, string VirtualID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ForgotPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ForgotPassword(string emailid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllImagesByVid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllImagesByVid(int userid, string VirtualID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteImagesByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteImagesByID(int ImageID, string ImageName, string virtualID, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTourByVID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteTourByVID(string virtualID, int userid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MLSDataWebServiceSoapChannel : Property1.MLSDataWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MLSDataWebServiceSoapClient : System.ServiceModel.ClientBase<Property1.MLSDataWebServiceSoap>, Property1.MLSDataWebServiceSoap {
        
        public MLSDataWebServiceSoapClient() {
        }
        
        public MLSDataWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MLSDataWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MLSDataWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MLSDataWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetResidentialProperties(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease) 
        {
            return base.Channel.GetResidentialProperties(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BedRooms, BathRooms, SaleLease);
        }
        
        public System.Data.DataTable GetResidentialPropertiesDetail(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease) {
            return base.Channel.GetResidentialPropertiesDetail(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BedRooms, BathRooms, SaleLease);
        }
        
        public System.Data.DataTable GetResidentialPropertiesTop3(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease) {
            return base.Channel.GetResidentialPropertiesTop3(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BedRooms, BathRooms, SaleLease);
        }
        
        public System.Data.DataTable GetResidentialPropertiesTop10(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease) {
            return base.Channel.GetResidentialPropertiesTop10(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BedRooms, BathRooms, SaleLease);
        }
        
        public System.Data.DataTable GetPropertyTypesResidential() {
            return base.Channel.GetPropertyTypesResidential();
        }
        
        public System.Data.DataTable GetPropertyTypesCommercial() {
            return base.Channel.GetPropertyTypesCommercial();
        }
        
        public System.Data.DataTable GetPropertyTypesCondo() {
            return base.Channel.GetPropertyTypesCondo();
        }
        
        public System.Data.DataTable GetPropertyTypesByMLSID(string mlsid) {
            return base.Channel.GetPropertyTypesByMLSID(mlsid);
        }
        
        public System.Data.DataTable GetSaleLeaseResidential() {
            return base.Channel.GetSaleLeaseResidential();
        }
        
        public System.Data.DataTable GetSaleLeaseCommercial() {
            return base.Channel.GetSaleLeaseCommercial();
        }
        
        public System.Data.DataTable GetSaleLeaseCondo() {
            return base.Channel.GetSaleLeaseCondo();
        }
        
        public System.Data.DataTable GetImageByMLSID(string MLSID_City_PostalCode) {
            return base.Channel.GetImageByMLSID(MLSID_City_PostalCode);
        }
        
        public System.Data.DataTable GetCommercialPropertiesByMLSID(string MLSID) {
            return base.Channel.GetCommercialPropertiesByMLSID(MLSID);
        }
        
        public System.Data.DataTable GetAllCommercialProperties(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BathRooms, string SaleLease) {
            return base.Channel.GetAllCommercialProperties(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BathRooms, SaleLease);
        }
        
        public System.Data.DataTable GetAllCommercialPropertiesTop3(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BathRooms, string SaleLease) {
            return base.Channel.GetAllCommercialPropertiesTop3(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BathRooms, SaleLease);
        }
        
        public System.Data.DataTable FeatureListing(string MLSIDs) {
            return base.Channel.FeatureListing(MLSIDs);
        }
        
        public System.Data.DataTable GetProperties_Condo(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease) {
            return base.Channel.GetProperties_Condo(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BedRooms, BathRooms, SaleLease);
        }
        
        public System.Data.DataTable GetProperties_CondoTop3(string MLSID_City_PostalCode, string propertyType, string MinPrice, string MaxPrice, string BedRooms, string BathRooms, string SaleLease, string Top) {
            return base.Channel.GetProperties_CondoTop3(MLSID_City_PostalCode, propertyType, MinPrice, MaxPrice, BedRooms, BathRooms, SaleLease, Top);
        }
        
        public System.Data.DataTable GetPropertiesByMLSID_Condo(string MLSID) {
            return base.Channel.GetPropertiesByMLSID_Condo(MLSID);
        }
        
        public System.Data.DataTable GetAutoCompleteData(string prefixText) {
            return base.Channel.GetAutoCompleteData(prefixText);
        }
        
        public System.Data.DataTable GetAutoCompleteData_Comm(string prefixText) {
            return base.Channel.GetAutoCompleteData_Comm(prefixText);
        }
        
        public System.Data.DataTable GetAutoCompleteData_Condo(string prefixText) {
            return base.Channel.GetAutoCompleteData_Condo(prefixText);
        }
        
        public System.Data.DataTable GetAllFeatures() {
            return base.Channel.GetAllFeatures();
        }
        
        public int DeleteFeatures(string MLSIDs) {
            return base.Channel.DeleteFeatures(MLSIDs);
        }
        
        public string GetAllVirtualTourData(int startindex, int pagesize) {
            return base.Channel.GetAllVirtualTourData(startindex, pagesize);
        }
        
        public string GetVirtualTourData(string MLSID) {
            return base.Channel.GetVirtualTourData(MLSID);
        }
        
        public string InsertVertualTourImages(string MLSID, string VimageBase64) {
            return base.Channel.InsertVertualTourImages(MLSID, VimageBase64);
        }
        
        public string IsValidMLSID(string MLSID) {
            return base.Channel.IsValidMLSID(MLSID);
        }
        
        public string Registration(string name, string emailID, string password) {
            return base.Channel.Registration(name, emailID, password);
        }
        
        public string AuthenticateUser(string emailid, string password) {
            return base.Channel.AuthenticateUser(emailid, password);
        }
        
        public string InsertVertualDetails(string virtualname, int userid) {
            return base.Channel.InsertVertualDetails(virtualname, userid);
        }
        
        public string InsertImageByVirtualName(string VirtualID, int userid, string VimageBase64) {
            return base.Channel.InsertImageByVirtualName(VirtualID, userid, VimageBase64);
        }
        
        public string GetAllOrSingleVirtDetailsByVid(int userid, int startindex, int endindex, string VirtualID) {
            return base.Channel.GetAllOrSingleVirtDetailsByVid(userid, startindex, endindex, VirtualID);
        }
        
        public string ForgotPassword(string emailid) {
            return base.Channel.ForgotPassword(emailid);
        }
        
        public string GetAllImagesByVid(int userid, string VirtualID) {
            return base.Channel.GetAllImagesByVid(userid, VirtualID);
        }
        
        public string DeleteImagesByID(int ImageID, string ImageName, string virtualID, int userid) {
            return base.Channel.DeleteImagesByID(ImageID, ImageName, virtualID, userid);
        }
        
        public string DeleteTourByVID(string virtualID, int userid) {
            return base.Channel.DeleteTourByVID(virtualID, userid);
        }
    }
}
