//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property.Admin {
    
    
    public partial class AnalyticStats {
        
        /// <summary>
        /// VisitorsOverview1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GADCAPI.VisitorsOverview VisitorsOverview1;
        
        /// <summary>
        /// ContentOverview1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GADCAPI.ContentOverview ContentOverview1;
        
        /// <summary>
        /// TrafficSourceOverview1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GADCAPI.TrafficSourcesOverview TrafficSourceOverview1;
        
        /// <summary>
        /// WorldMap1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GADCAPI.WorldMap WorldMap1;
    }
}
